# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  #adapter: sqlite3
  database: javi
  username: root
  password: root
  pool: 5
  timeout: 5000